# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=200)),
                ('away', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2016, 2, 11, 23, 27, 16, 705297, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
